### ISSUE TITLE
Some Feedback

### ISSUE THREAD

**Issue by JourneyHua** [Slyyxp/BugsPy#1]
Download this [album](https://music.bugs.co.kr/album/20343349) can get the flac file, 
<img src="https://files.catbox.moe/s8zp6o.png">
And this [album](https://music.bugs.co.kr/album/20343816) only track1 is a flac file, others are flac but can't play ,Actually, when I change *.flac to *.mp3, they can play. :)
<img src="https://files.catbox.moe/n5xv5m.png">
Others:
<img src="https://files.catbox.moe/3l1if7.png">

Sorry,maybe my english is so bad ::

**Comment by Slyyxp** [comment]
"Others" unfortunately does not help me troubleshooting.
Album ID's of successful albums have no use to me.

You need to provide the ID of the failing albums.

**Comment by JourneyHua** [comment]
Okay, there are some failing albums:
https://music.bugs.co.kr/album/197341
https://music.bugs.co.kr/album/992177
https://music.bugs.co.kr/album/14116820
https://music.bugs.co.kr/album/20338505
https://music.bugs.co.kr/album/20262506
https://music.bugs.co.kr/album/990741

**Comment by Slyyxp** [comment]
Pulling the latest commit should resolve this issue.
https://github.com/Slyyxp/BugsPy/commit/91e54c67e1c1ee14da5cb3318abfbc1689157eb2

**Comment by JourneyHua** [comment]
Actually, it's still has some problem.
These failing albums I still can't download them.
[album](https://music.bugs.co.kr/album/197341)
<img src="https://files.catbox.moe/by7uwy.png">
[album](https://music.bugs.co.kr/album/992177)
<img src="https://files.catbox.moe/8hnuj8.png">

**Comment by Slyyxp** [comment]
These particular albums both work fine on my end.
It seems like although the request for FLAC is going out Bugs are re-directing you to the MP3.

Pull the latest commit and send the contents of your log file.
https://github.com/Slyyxp/BugsPy/compare/91e54c67e1c1...c950e79fc39b

**Comment by JourneyHua** [comment]
<img src="https://i.loli.net/2020/08/20/iWX1zeCQp62hIMD.png">
This is the log of the two albums just now

**Comment by Slyyxp** [comment]
You have not pulled the latest commit.

`$ git pull`

Run the above line or re-download the zip from the repo.

**Comment by JourneyHua** [comment]
I'm sure I have been git... and again..
<img scr="https://i.loli.net/2020/08/20/VRvrgncakxpObsX.png">

**Comment by Slyyxp** [comment]
Your account is not eligible for FLAC streaming.

**Comment by JourneyHua** [comment]
WTF...
<img src="https://i.loli.net/2020/08/20/HnsDYTB7JZ6UMp3.jpg">
but I have been the VIP
<img src="https://i.loli.net/2020/08/20/WS38roFuTPRv9xj.jpg">
and can choose the flac

**Comment by Slyyxp** [comment]
I'm not sure on the difference of the VIP plan so I cannot elaborate on why you are not eligible.
`Premium 듣기` is the expected plan of the user.

I have pushed a new commit which should give you a more detailed look about your stream eligibility.
https://github.com/Slyyxp/BugsPy/commit/5e84ad438cc89d35d77660e34be2fbbd4276483b

**Comment by JourneyHua** [comment]
Thanks, my plan is 듣기(매월) , I think choose auto subscribe is a wrong...
I try to create another account, and buy again...

**Comment by JourneyHua** [comment]
Finally, I paid wrong at first, and pay again just now.
<img src="https://i.loli.net/2020/08/20/DOzdt6kqXZwh1Qu.png">
Now, it works well :)
<img src="https://i.loli.net/2020/08/20/A3dJKe6UpaXP4Yq.png">
Thank you very much Slyy! ❤U
